### ISSUE TITLE
Keep asking for update.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [saVantCZ/PS5reborn#1]
Keep asking for updating from 1.0 -> 1.0.0
Tried uninstalling and reinstall, still same.

Let me know when this is fixed. Uninstall for now.

**Comment by saVantCZ** [comment]
Will be fixed in next update, i think I got manifest wrong

**Comment by syaifulnizamyahya** [comment]
Fixed it myself. Just edited the Version from
Version: 1.0
to
Version:1.0.0
in theme.yaml file.

Thanks.
