### ISSUE TITLE
Weird Reddish Color at the beginning or boot up screen of the theme

### ISSUE THREAD

**Issue by HuzKunstler** [saVantCZ/PS5reborn#11]
I've installed all the addons the right way everything works fine and great, but i have this problem that the boot video seems to be a reddish color but only in boot as I've attached an image below
![Screenshot 2024-08-14 094111](https://github.com/user-attachments/assets/32b12768-fe7a-4bf5-ba1e-b0e868025f7e)
![Screenshot 2024-08-14 094141](https://github.com/user-attachments/assets/204d49da-c57c-43ca-998b-b52742ce375f)

what i've checked, i've tried changing the format of intro videos to other formats like mkv and all but nothing works except mp4, and any mp4 video seems to be doing the seem it's not a media issue i assume. please take a look at this problem.

Regards

**Comment by saVantCZ** [comment]
Videos in playnite are rendered with Windows Media Player... you should check if you have some color profile set for video playback in GPU settings or windows media player settings.
