### ISSUE TITLE
[Feature Request] Change the size of covers in the theme

### ISSUE THREAD

**Issue by FoxyCantCode** [saVantCZ/PS5reborn#12]
Hey, great theme, I love it! seriously

but a feature for changing the cover size like in the PS5ish theme would be really good. Lots covers really don't look good without actually as compared to medium since its too small to see properly

**Comment by Zer0Rem** [comment]
That would be awesome.
 i used the PS5ish Theme before and  really miss the bigger Game covers

**Comment by saVantCZ** [comment]
Started working on code rewrite to toggle small (regular PS5 size) and big, which would be 1.25x bigger

No ETA, but its work in progress.

**Comment by saVantCZ** [comment]
Added in 1.5.0
