### ISSUE TITLE
Trophy Counter Fix

### ISSUE THREAD

**Issue by Jaralus** [saVantCZ/PS5reborn#14]
Hi I couldn't create a pull request because the full code isn't there but I managed to fix the trophy counter. Albeit not the most elegant of fixes.

![image](https://github.com/user-attachments/assets/84325a58-c1c7-4573-9e80-204b63d9ceda)

![image](https://github.com/user-attachments/assets/f7f7d9dd-add8-4626-8f97-e868daac0732)

Fixes are displayed in the images above. How can I contact you to send over the files.

**Comment by saVantCZ** [comment]
Will add this feature when successtory plugin is fixed. For me its broken.

**Comment by Jaralus** [comment]
No worries, just let me know if you want to see my code.
