### ISSUE TITLE
Disable non-usable items

### ISSUE THREAD

**Issue by felipecustodio** [saVantCZ/PS5reborn#2]
Hi there, great project, loving the theme.

I would like to know if it's possible to edit the theme or add options to disable options that are not usable, like the fake PS Store, Game Policy button, things like that.

I understant that it's mimicking the complete look of the PS5, which you nailed btw, but since it's a theme for a console-like experience for PC, would be nice if it could be streamlined to only have things that can be used. Just an option to toggle or instructions on how to disable elements by editing the theme would be nice.

Thanks!

**Comment by saVantCZ** [comment]
Sure, i completely understand and yes, i can add "switch" to disable useless elements

**Comment by saVantCZ** [comment]
Most of the useless stuff can be disabled via Theme Options
