### ISSUE TITLE
after restarting pc fullscreen mode doesnt work with splash screen

### ISSUE THREAD

**Issue by rulelol** [saVantCZ/PS5reborn#20]
it works normally when you first install the addon but if you restart pc cant move in fullscreen mode please fix really need that addon...

**Comment by saVantCZ** [comment]
Can you elaborate problem more?

Controller stop working after restart? Does keyboard move works? If you disable splashscreen it works again after restart?

Splashscreen plugin should not interfere with Theme in any way.

**Comment by rulelol** [comment]
turns out its not Splashscreen yeah since it happened to me again i will try to figure out what i did so i see whats causing it

**Comment by saVantCZ** [comment]
Make sure some other programs doesnt steal focus, or if using some kind of controller mapping tool or xinput emulators, make sure in fullscreen playnite settings, input, is your controller active

**Comment by rulelol** [comment]
cant move around in fullscreen and i have this black lines https://prnt.sc/ebkGFZqXc7sJ

**Comment by rulelol** [comment]
ok its happening because of ds4 windows

**Comment by rulelol** [comment]
i have game controller support on is there anything else i can do

**Comment by saVantCZ** [comment]
Open settings in fullscreen, select input, and check if there are more then 1 controllers in settings... it looks like playnite is receiving more clonned inputs

**Comment by saVantCZ** [comment]
Can happen if you connect controller during on after playnite loading, try connect your controller first then launch playnite

**Comment by saVantCZ** [comment]
Playnite should work with controller without ds4win, if your games needs it, you can create script when game launch it launches ds4win and then close it when game closed.

Its common problem

**Comment by saVantCZ** [comment]
And i think you can disable "clonned" controller inside Input playnite settings, that way it should be fixed

**Comment by rulelol** [comment]
where exacly is that setting i cant see it anywhere

**Comment by rulelol** [comment]
![image](https://github.com/user-attachments/assets/bdcea57f-9fe3-42a2-93f6-1c0729dd7d44)

![image](https://github.com/user-attachments/assets/a662cd6a-d71f-4889-92cc-19411d433841)

**Comment by saVantCZ** [comment]
If you open ds4w and launch it again, check settings from second picture if there are more then 1 controllers... if its true, disable virtual controller created by ds4w.

On second screenshot it is how it should look, only one controller active

**Comment by rulelol** [comment]
![image](https://github.com/user-attachments/assets/46716e7b-67c7-4819-9673-737f11070e16)

**Comment by rulelol** [comment]
putting it like this fixed it thank you alot

**Comment by saVantCZ** [comment]
Glad i could help!
