### ISSUE TITLE
Higher CPU utilization while in background

### ISSUE THREAD

**Issue by rwifislax** [saVantCZ/PS5reborn#21]
Starting a game and then launching task manager to see the CPU usage, I have noticed this theme uses more CPU than, for example, PS5ish while in background. PS5ish stays around 0% - 0.2%. I have seen this theme around 0% - 0.6%, and consistently stay around 0.1-0.4% CPU usage. I wonder if the CPU utilization while in background can be lowered.

**Comment by saVantCZ** [comment]
Compare features for PS5ish snd PS5reborn.

My theme has so much more stuff, more animatons, more elements, more of everything.

You can try and disable some features via Theme Options if it helps.

**Comment by saVantCZ** [comment]
Found out in latest update, welcome hub video background is still loaded even when its disabled in theme options. Will be fixed in next update
