### ISSUE TITLE
Turn Off System in menu doesn't turn off PC

### ISSUE THREAD

**Issue by thedrunkgod** [saVantCZ/PS5reborn#23]
On the latest update, pushing turn off system from the menu only closes Playnite and doesn't turn the PC off.

**Comment by saVantCZ** [comment]
https://github.com/ashpynov/PlayniteSound/issues/13

**Comment by saVantCZ** [comment]
Issue reopened

**Comment by saVantCZ** [comment]
Issue reopened

**Comment by saVantCZ** [comment]
Looks like one of my triggers prevents in turning off PC, will be fixed in new update

**Comment by saVantCZ** [comment]
Was fixed on Playnite Sounds Mod side 5.7.15 version
