### ISSUE TITLE
Clarifications on personalization

### ISSUE THREAD

**Issue by foss-lover34** [saVantCZ/PS5reborn#24]
Im still not able to remove the fake notification icon, the fake ps store and fake ps plus altough i see you talking about it like you can disable it with theme options plugin in a closed ticket. but i cant find what you are referring to. please answer me and let me know how to remove these few things because im literally in love with this theme

**Comment by saVantCZ** [comment]
Make sure you updated theme and have theme options addon installed.

Open fullscreen, settings, there should be Theme Options. Disable PlayStation store, disable Welcome Hub. You can also disable intro video and press the button/profile selector screen.

**Comment by foss-lover34** [comment]
Ah you are right, thank you very muhc. one last thing, could you also add a toggle to remove the fake notifications?

one last issue i have is i cant setup all the plugins in a cool way in fullscreen mode like you did in you example picture. like i had default playnite. put all the settings you did with all the plugins, but on gta 5 i still cant see success story (also how to manually add the achivements), or how long to beat, heck i dont even see the notes which should be playnite default. could you help me with that

**Comment by saVantCZ** [comment]
What is fake notification? Can you send me screenshot of what you mean by that?

Success Story works well with original games, if you want manual ones you still need steam API so exophase works (steam api key only if you spend more then 5$ on steam)

Howlongtobeat should work if you link hltb account to it. Then in desktop mode right click on game, howlongtobeat and download data.

Notes are when you edit game in desktop mode and select advanced tab, there is note, just type in any text and save

Every addon has its own github page and setup tutorial are there.

**Comment by foss-lover34** [comment]
hello again.

i mean the notification icon right next to the clock on the top right. is there any way to remove it?
![image](https://github.com/user-attachments/assets/e594e452-7444-4032-a52f-1f5d0a50eb23)

is there any way to add how long to beat data manually? i think having to log in into a service only to get literally a small string of text is kinda insane! Same thing for success story and trophies, i wish i could add them manually and offline-


And finally for extra metadata. if i manually add a trailer it will appear on the media section right? like in you pictures

but what about the microvideos for the background where do i put those?


thank a lot for all the patience you ahd with me! my doubs are all finished after this !

**Comment by saVantCZ** [comment]
Notification icon is not actually fake, it has purpose,  if there is playnite update it glows green, if there is no update its gray.

No idea about HLTB manually sorry, you need to ask Plugin developer 

Same goes for success story, i have no idea because i dont use manual trophies, all my games are from steam and works 100%.

You can right click on game, select extra metadata and click on micro trailer > generate micro video from downloaded trailer, or something like that, it will generate it for you

**Comment by saVantCZ** [comment]
You can also download trailers with plugin, all by right clicking game in desktop mode. You just need to setup plugin correctly, but you can find tutorial on extrametadata github page of developer.

**Comment by foss-lover34** [comment]
all clear now boss. thanks a lot for everything. basically im just sad 1/3 of the widgets of the game (success story) i cant do anything without the steam api and im so very sad for that and that space is just wasted so maybe if there was a replacement of some kind, of any widget at all.

Anyways i dont really care about that, eventually maybe ill figure it out by asking the original devs like you said.
what i wanted to ask is you dont think its possible to add a toggle to remove the notifications icon? honestly its hardly ever that its actually useful. also it literally has a different background color that makes it stick out like a sore thumb. idk if its possible but removing it would be dope af because at the end of the day its purposeless ugly etc.

**Comment by saVantCZ** [comment]
You can edit main.xaml, find NotifLight and change its Fill= to "Transparent" as well as changing TargetName="NotifLight" Property="Fill" Value="Gray" Gray to Transparent

For success story, well... minimal $5 isnt that much nowadays.

**Comment by foss-lover34** [comment]
Yeah sure it isnt much but the fact is i mostly have emulated games and drm-free version of pc games so i just wish i could add them manually. Thanks for everything dude! This theme is friking awesome!!
