### ISSUE TITLE
After the last update the group games not opening 

### ISSUE THREAD

**Issue by Momenayad** [saVantCZ/PS5reborn#26]
I just updated to last version unfortunately everything was perfect for me but the group icon that in real all games now I can't select it or open it I don't know what's wrong could you fix that please I really like that theme 
thank you

**Comment by saVantCZ** [comment]
Sorry i dont understand exactly what problem is

**Comment by Momenayad** [comment]
![IMG_6202](https://github.com/user-attachments/assets/a59e0857-0f4e-49dc-84a7-fc0719ccd1a2)

Thank you for your prompt response. Sorry, but I mean This icon (games library) in the image. I can't select and I don’t know why. And btw I use the theme on Asus Rog ally x so I tried touching it but not function too

**Comment by saVantCZ** [comment]
How many games do you have on main screen? Its less then 10? I am trying to recreate the issue but its working for me no problem.

**Comment by Momenayad** [comment]
I have 10 games

**Comment by saVantCZ** [comment]
It could be that your Ally is creating double input, and it skips... check fullscreen settings -> Input and uncheck all other "controllers" and keep only one.

**Comment by saVantCZ** [comment]
Hope it solved your problem, i am pretty sure its double input related.

**Comment by Momenayad** [comment]
Unfortunately, I downloaded 1.7 yesterday and still can't access the game Library icon. I am out for work now once I get back home i will shoot a video for you 
Thanks

**Comment by saVantCZ** [comment]
As insaid, disable any other input in fullscreen settings and keep enabled only one 

This is not theme related problem

**Comment by novelandoweb** [comment]
I'm also having the same problem. In version 1.5 everything works normally. However, in the current 1.7 the icon that accesses the games is inaccessible. I tried to see the tutorial given here, but I couldn't find the part on Playnite to check which icons are selected in full scream.

**Comment by saVantCZ** [comment]
Do you have horizontal scrolling OFF in layout settings?

Please check Input settings if there is only 1 controller active.

I still cannot reproduce this issue.

Also how much games do you have in current active filter preset?

**Comment by novelandoweb** [comment]
I discovered what is happening. As I like to see the games in the library with a greater zoom, I was setting the lines to 3 (see
 the photo). However, any number greater than 2 makes the group icon inaccessible.

![playnite-ps5](https://github.com/user-attachments/assets/69159927-6cf3-4f57-a2ab-75c32ff27a73)

**Comment by novelandoweb** [comment]
it was fixed in the latest version (2.0.0). thanks.
