### ISSUE TITLE
After plugin updates some functionalities don't work

### ISSUE THREAD

**Issue by rwifislax** [saVantCZ/PS5reborn#27]
After the latest plugin update, I saw improvement on the background performance, and menu responsiveness, also the images resolution from steam was improved. However, the intro video no longer plays, and there is a black screen at the profile screen. The game videos no longer play either, and no sound for the games from playnite sound mod, or the background.

**Comment by saVantCZ** [comment]
Looks like problem with windows media player.

**Comment by rwifislax** [comment]
You are right, I had removed that optional feature on Win 11 because it said legacy and thought I didn't need it, turns out Playnite needs Windows media Player for audio and video. Got fixed after adding it again. You the man. Thank you.
