### ISSUE TITLE
How to play videos in the game background

### ISSUE THREAD

**Issue by foss-lover34** [saVantCZ/PS5reborn#33]
Hello mate, thanks for all the awesome updates recently to this project. it really improved tons and i love how dedicated you are and i want to thank you again. After following your suggestions i went back to windows media player windows version, and now the intro plays  beautifully (even the 4k one!) (regarding this i wanted to ask if it was possible for you to create a custom version of the startup screen where epilepsy warning is not there ruining the aestethic, or alternatively use this less cluttered version https://www.youtube.com/watch?v=b6Mp13Ole90 with just a line)

anyways. i wanted to ask better clarification on how to play a background video on the game. i have extra metadata and every plugin you told me to install, the intro video plays, also the one from the welcome hub, also i setup a background music for my games successfully and after manually selecting a video from playnite > extra metadata and then generating a microvideo still from extra metadata settings, it finally showed up in theme fullscreen. i would like it to be like this: you go to a game, music start and image shows, after like 4-5 seconds the video starts, when it finishes the image comes back. Please help me out on this its the last step for me.

**Comment by foss-lover34** [comment]
basically i just want the video to start 4-5 seconds after i highlight a gme. pls tell me how

**Comment by foss-lover34** [comment]
Actually i just reliazed i can ditch the static background image alltogether, and make a modified background video on some editing sofftware where i put the static background then wait some seconds and start the trailer. it would be a lot of work so still let me know if you can help

**Comment by foss-lover34** [comment]
also another quick question how can i delay the playing of the sound when i highlight a game? still, this could be solved with editing but please let me know any other ways

**Comment by saVantCZ** [comment]
You can wait for next update, i will implement this by code

**Comment by foss-lover34** [comment]
> You can wait for next update, i will implement this by code

the sound thing i mentioned in the last comment as well?

**Comment by saVantCZ** [comment]
> > You can wait for next update, i will implement this by code
> 
> the sound thing i mentioned in the last comment as well?

No, you can play with fade in/out delay in sounds mod settings

**Comment by foss-lover34** [comment]
YO IM SO HAPPY !! so basically after an update i will be able to set a delay for when the video starts? and before it starts it just shows the background image? THATS amazing!

for the sound issue, sadly even with maximum delay it doesnt work as intended, but fear not, i will fix it manually by editing, im just happy i wont have to do that with videos

**Comment by foss-lover34** [comment]
btw one thing is still not clear to me, where do i need to place the steam screenshots?

![image](https://github.com/user-attachments/assets/1044b308-d2d4-4a8e-aa06-a66db72f69c2)

i dont see any way to download them or to set their location, i isntalled both steam store screenshot visualizer and screenshot visualizer, but i cant set them, also i notice there are only 3 screenshot in your picture is that the limit?

**Comment by saVantCZ** [comment]
Game needs to have steam url in links set

**Comment by foss-lover34** [comment]
great i did that! is there any way to use local files instead of links tho? please tell me there is

**Comment by foss-lover34** [comment]
> You can wait for next update, i will implement this by code

btw this feature will also increase performance because it doesnt have to load the video right away

**Comment by saVantCZ** [comment]
> great i did that! is there any way to use local files instead of links tho? please tell me there is becasue my system lags like crazy when loading the images
> 
> and how to show more than 3 screenshots?

It will lag only once, its creating cache... once images are downloaded it will use LOCAL cache which will reload from steam every 12-15 days.

**Comment by saVantCZ** [comment]
> > You can wait for next update, i will implement this by code
> 
> btw this feature will also increase performance because it doesnt have to load the video right away

Its gonna be same, doesnt matter when video will play

**Comment by foss-lover34** [comment]
wow, well what can i say, i fixed all my issues and im very happy, i also succesfully setup howlongtobeat and success story, as well as trailer, microvideo background, background music. cant wait to share everything once this last update comes out!

sadly i have one final performance issue, when a game is fully set up like this (in my example gta 5) when i scroll down to the game it lags like crazy when it has load the steam screenshot so i think i should find the local files, change the resolution and that should fix it right? 

also switching between games is not super smooth so how could i also improve performance on that side? just lowering the resolution? i just wish i could just wait a bit before playing the video so that if i go trough my library quickly it wont stutter.

**Comment by foss-lover34** [comment]
this is what i mean, the first big freeze of SECONDS when i go down in gta 5, and the stutter when quickling going trough games 


https://github.com/user-attachments/assets/f6fad554-e568-4fe6-b075-3d7cc3ef262e

**Comment by saVantCZ** [comment]
In desktop mode, click menu (orange controer icon) select extensions, extrametadata and select set profile picture. This way you can change default black profile picture to your own

Also, you can enable "profile selector" switch in theme options, so instead of press the X button after intro you will have "welcome back" screen with profile selection

There is one plugin which can optimize metadata images size, you can use it to reduce 4k background images to 1080p and improve performance

**Comment by foss-lover34** [comment]
i dont really care about setting a profile picture, i like the default one i just want it to have transparent background.

i dont get whawhat about the performance issues

**Comment by saVantCZ** [comment]
Reduce images size, as I said there is plugin for it

**Comment by foss-lover34** [comment]
yeah but does the profile pixture image support transparent background? that way i can fix that other issue with the black background

**Comment by saVantCZ** [comment]
Find default picture in theme folder and edit it however you need

**Comment by foss-lover34** [comment]
but why does the startup video now lag so much? it didnt before i started adding the video backgrounds. whatever i guess its hardware issue? im looking for help tho!

and the very final suggestion for the final immersion effect,and this would be fucking awesome to have as cherry on top, as you can see in the video up here when i press x to enter the home or when i select the user for the same reason it immediatly shows the background image of the first game, and the video starts, but the whole menu is not even loaded! it should show the generic ps5 background and then when the hub is loaded it should switch to the image/video. dont you think?

**Comment by foss-lover34** [comment]
ill leave this suggestion in here, please consider it. now i go to sleep cuz i worked all night on setting everything up

**Comment by saVantCZ** [comment]
It was changed in new versions, in older builds 1.X.X it did shows generic ps5 background before everything loaded

I changed it because i hate it

**Comment by saVantCZ** [comment]
About performance, i have ryzen 3600 and gtx 1070ti... its kinda low/mid build, but everything is smooth even with 4k images and videos. So your pc might be even lower then mine

**Comment by foss-lover34** [comment]
> It was changed in new versions, in older builds 1.X.X it did shows generic ps5 background before everything loaded
> 
> I changed it because i hate it

please man you gotta add it as an option because you hated the way it was before but i dont like how it is now because i dont think it makes much sense to show random game before anything esle. please

**Comment by foss-lover34** [comment]
> About performance, i have ryzen 3600 and gtx 1070ti... its kinda low/mid build, but everything is smooth even with 4k images and videos. So your pc might be even lower then mine

i have 1050ti and i5 6500 so maybe its too low ? well the intro loaded fine even in 4k issues araised when i put microvideo as background on various games

**Comment by saVantCZ** [comment]
Micro video constantly loops in background with gpu decoding and usage up to 10 percents.

**Comment by foss-lover34** [comment]
yeah but shouldnt that happen only when i highlight the game? it seems like every video loads at the same time and makes everything lag

**Comment by saVantCZ** [comment]
Yes only for selected game, still gpu is used for video decoding. 1050ti isnt really great tbh, everything you see happening on screen, animations, handling images, transitions, fade in and out, is handled by gpu because its hw accelerated.

Theme is not really low end friendly.

**Comment by foss-lover34** [comment]
ok then i just need one more thing, i need some help to find the local cache of steam screenshot visualizer because everything i load them my playnite freezes so i want to know where they are locally so i can edit them to make them more performance friendly, and to disable the automatic refresh from steam page. maybe you could add an option to load 3 screenshots locally. please, i really want to have the screenshot visualizer but it lags everything i go down there

**Comment by saVantCZ** [comment]
You can disable steam screenshots in theme options and just use screenshot visualiser plugin, but you need to set it up, i will not help you with that, you can check its github page for more info

Screenshot visualiser plugin alllows using custom screenshots for games, you can use anything here

Cache for steam screenshots is located in extensionsdata

**Comment by foss-lover34** [comment]
btw i noticed that from the game page, if i continue to press down from "play game" to the trophies widget and the down again it correctly goes to the media section, as expected, but the same doesnt happen when you press down starting from the notes widget or the how long to beat widget and in these cases it goes directly to the game legal info

**Comment by foss-lover34** [comment]
> You can disable steam screenshots in theme options and just use screenshot visualiser plugin, but you need to set it up, i will not help you with that, you can check its github page for more info
> 
> Screenshot visualiser plugin alllows using custom screenshots for games, you can use anything here
> 
> Cache for steam screenshots is located in extensionsdata

thats fucking amazing and just want i wanted to hear, so basically your amazing theme can also load 3 local images by simply using the screenshot visualizer plugin?

**Comment by saVantCZ** [comment]
> > You can disable steam screenshots in theme options and just use screenshot visualiser plugin, but you need to set it up, i will not help you with that, you can check its github page for more info
> > Screenshot visualiser plugin alllows using custom screenshots for games, you can use anything here
> > Cache for steam screenshots is located in extensionsdata
> 
> thats fucking amazing and just want i wanted to hear, so basically your amazing theme can also load 3 local images by simply using the screenshot visualizer plugin?

You can also use both, 3 from steam 3 local from screenshot visualier, making it 6 in total on game page

**Comment by saVantCZ** [comment]
If you wish to continue with discussion, please message me on Discord. I will close this one, because this is not really chat room.

**Comment by foss-lover34** [comment]
sure boss but i configured screenshot visualizer and selected a folder with 3 simple images but they dont show up in the theme like the links did

**Comment by saVantCZ** [comment]
Lets continue on discord please.

**Comment by foss-lover34** [comment]
sure, sorry for disturbing, please let me know your discord contact

**Comment by saVantCZ** [comment]
savantcz

**Comment by ElTioRata** [comment]
I don't quite understand any of your messages. How do I set this up?

**Comment by saVantCZ** [comment]
> I don't quite understand any of your messages. How do I set this up?

Make sure to have extrametadata and extrametadata fullscreen helper extensions, set everything up in extension settings, like ffmpg path and others ... then you can in desktop mode select all games with ctrl+a, right click, select extrametadata and choose microtrailer download, or first download trailer then generate microvideo.

Then you can in theme options choose micro trailers as background

**Comment by ElTioRata** [comment]
Hey, would it be possible to implement a feature that allows me to apply blur to the videos? Some of the ones that I downloaded doesn't have very good quality.

**Comment by saVantCZ** [comment]
Trailers from youtube are downloaded in low quality, use download from steam or scrap youtube videos yourself, then just replace file in extrametadata folder

**Comment by ElTioRata** [comment]
I don't think I can find Hot Pursuit 2 opening on Steam, besides I already looked up on YouTube for better quality sources and I couldn't found anything besides poor AI upscales. I'd be better to just hide the low quality.
