### ISSUE TITLE
How to delete PS5 GAME Privacy Policy content

### ISSUE THREAD

**Issue by sesxc1** [saVantCZ/PS5reborn#36]
How to delete PS5 GAME Privacy Policy content？
![12](https://github.com/user-attachments/assets/38d0675f-e4ee-4074-b783-b00e66ee440b)

**Comment by saVantCZ** [comment]
Content or whole windows?

**Comment by saVantCZ** [comment]
Can be disabled in Theme Options in 2.4.0 version

**Comment by sesxc1** [comment]
thanks!
