### ISSUE TITLE
Hidden Trophies/Achievements

### ISSUE THREAD

**Issue by geenaxion** [saVantCZ/PS5reborn#38]
Not really an issue but a request/suggestion.

On Desktop mode, the hidden achievements are hidden/blurred description and title.
But when it comes to the Ps5reborn fullscreen, all the trophies are visible even those supposedly hidden trophies.

An option to blurred/hide the description and title of the hidden trophies would be nice. 

thank you

**Comment by saVantCZ** [comment]
Yes good suggestion, will implement

**Comment by saVantCZ** [comment]
Added in 2.5.0, enjoy
