### ISSUE TITLE
How do I add the platform logo right before the name of the game?

### ISSUE THREAD

**Issue by ElTioRata** [saVantCZ/PS5reborn#4]
Like in the screenshots

**Comment by saVantCZ** [comment]
Open library manager in desktop playnite or ctrl+w (I think) and select platform on left side, then choose whatever platform you wanna change and on right side choose icon for it. 

Icons are in playnite/themes/fullscreen/ps5reborn/images/platforms

**Comment by ElTioRata** [comment]
Thx.

Too bad that none of the icons are for the platforms that I need :B (specifically: PS2, PS3, Xbox Classic, Xbox 360, GameCube, Windows or just a generic PC label).

**Comment by saVantCZ** [comment]
I can make these in future update... for now you can use Photoshop to edit and create it yourself

**Comment by ElTioRata** [comment]
Just made some. Feel free to add them.

![XboxClassic](https://github.com/saVantCZ/PS5reborn/assets/19964653/eabe41fe-c82a-477c-a3d5-1500b5950099)
![Xbox360](https://github.com/saVantCZ/PS5reborn/assets/19964653/86c3fc11-400c-4e9f-9f15-4cf8c030fc96)
![PS2](https://github.com/saVantCZ/PS5reborn/assets/19964653/1a903bf3-54a6-4148-993e-24e00bbd5f7f)
![PS3](https://github.com/saVantCZ/PS5reborn/assets/19964653/1febb1b2-1907-4a44-9249-eb407172baac)
![GFW](https://github.com/saVantCZ/PS5reborn/assets/19964653/bf005f5a-dcac-46e0-83f5-c337a1d49219)
![GFWL-alt01](https://github.com/saVantCZ/PS5reborn/assets/19964653/a8f0ea2b-3f64-4a6c-baf1-87a7e9415e1e)
![GFWL-alt02](https://github.com/saVantCZ/PS5reborn/assets/19964653/7bc39336-99b9-4c42-908a-ac65c1fb5f37)
