### ISSUE TITLE
[Feature request] Add size option for vertical cover art layout

### ISSUE THREAD

**Issue by OdinIsLord** [saVantCZ/PS5reborn#5]
First of all, absolutely astonishing work on the trophies. Looks so good and professional.

One small feature to implement would be having the option to choose the cover size in the main menu. Changing it to from small to medium would allow to take advantage of vertical cover arts like on PS5ish:

![Playnite FullscreenApp_kQa3Y2iBXv](https://github.com/saVantCZ/PS5reborn/assets/97923430/93f3a364-77bc-4bc9-a3bc-768e01b5e093)

![Playnite DesktopApp_pz2NqZESci](https://github.com/saVantCZ/PS5reborn/assets/97923430/fe1b5c9a-f9f8-4f66-a688-a58bba8e34ef)

**Comment by saVantCZ** [comment]
It is possible to add, but that means rewrinting good chunk of code to support it, especially animation of game list for different size and variations of position for game title for each size.

**Comment by saVantCZ** [comment]
I am using totally different approach then PS5ish, so its not that simple

**Comment by OdinIsLord** [comment]
Would be a welcomed addition nonetheless, especially for already established libraries.

**Comment by saVantCZ** [comment]
Vertical Covers will not be added anytime soon

Size to 1.25x can be toggled via Theme Options plugin in v1.5.0

**Comment by saVantCZ** [comment]
> Would be a welcomed addition nonetheless, especially for already established libraries. Wish I could help.

Support for 3:4 cover images will be avaiable in next update
