### ISSUE TITLE
the intro video does not show, it just shows a black screen

### ISSUE THREAD

**Issue by nachouuu** [saVantCZ/PS5reborn#7]
When full screen mode is started, the intro video does not play, only the text "press the (A) button on your controller" is displayed

**Comment by nachouuu** [comment]
https://github.com/saVantCZ/PS5reborn/assets/147904803/959b59d3-34dc-45ae-ac0a-60b1c9d11041

**Comment by saVantCZ** [comment]
Your windows does not have media player installed.

**Comment by saVantCZ** [comment]
![Screenshot_20240708_183140_Edge](https://github.com/saVantCZ/PS5reborn/assets/97293893/9514dcf3-b659-4595-af3b-54fc42b9b8fc)

**Comment by nachouuu** [comment]
thanks bro
